spring.application.name=backend

# Puerto
server.port=8080

# SQL Server
spring.datasource.url=jdbc:sqlserver://${SQL_SERVER_NAME}.database.windows.net:1433;database=${DATABASE_NAME};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

spring.datasource.username=${SQL_ADMIN_LOGIN}
spring.datasource.password=${SQL_ADMIN_PASSWORD}

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect